---
services:
  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=courier
      - POSTGRES_PASSWORD=courier
      - POSTGRES_DB=courier

  app:
    # image: courier-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=courier
      - DB_PASSWORD=courier
      - DB_NAME=courier
    depends_on:
      - db

    command: sh -c "node dist/main.js"
